# Generated by Django 5.2 on 2026-09-10 22:21

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pages.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('mesero', 'Mesero')], default='cliente', max_length=20),
        ),
    ]
