# Generated by Django 5.2 on 2026-09-11 03:18

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('carnes', 'Carnes'), ('vegano', 'Vegano'), ('bebidas', 'Bebidas')], default='carnes', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=30)),
                ('imagen', models.URLField(blank=True, max_length=500)),
                ('disponible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alergenos', models.ManyToManyField(blank=True, related_name='items', to='menu.alergeno')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
